# add site config
<VirtualHost *:443>
    DocumentRoot /app

    SSLEngine on
    SSLCertificateFile "/etc/apache2/ssl/ssl.crt/server.crt"
    SSLCertificateKeyFile "/etc/apache2/ssl/ssl.key/server.key"

    #WSGIDaemonProcess backend user=appuser group=appuser python-home=/usr/local/bin python-path=/app
    WSGIDaemonProcess backend user=appuser group=appuser python-path=/usr/local/bin/python3
    #threads=1 processes=16 maximum-requests=1000 graceful-timeout=3600 socket-timeout=1800 request-timeout=1800
    WSGIScriptAlias /backend /app/logger/wsgi.py
    WSGIPassAuthorization On

    <Directory /app>
        #Options +Indexes
        WSGIProcessGroup backend
        WSGIApplicationGroup %{GLOBAL}
        WSGIChunkedRequest On
        Order allow,deny
        Allow from All
        Satisfy any
        Require all granted
    </Directory>

    <Directory /app/logger>
        <Files wsgi.py>
            Satisfy any
            Require all granted
        </Files>
        Satisfy any
        Require all granted
    </Directory>

    Alias /static /app/static

    <Directory /app/static>
        Order allow,deny
        Allow from All
        Satisfy any
        Require all granted
    </Directory>
</VirtualHost>